version: "3.8"

## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION   ##

name: hello-dev

services:
  backend:
    container_name: backend-dev
    image: hello-backend-dev
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - 8080
    ports:
      - "8080:8080" # database port (host:container)
    env_file:
      - .env
    volumes:
      - ./:/app
    networks: 
     - network-backend

  postgres:
    container_name: postgres-dev
    image: postgres:alpine
    user: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data # postgres-data: ./postgres-data:
    expose:
      - 5432
    ports:
      - "5432:5432" # database port (host:container)
    env_file:
      - .env
    networks: 
      - network-backend
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    container_name: redis-dev
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - postgres-data:/var/lib/redis/data
    networks: 
      - network-backend

networks:
  network-backend:
volumes:
  postgres-data:
    external: true
    name: postgres-data

  redis-data:
    external: true
    name: redis-data