version: '3.5'

## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION   ##

name: hello

services:
  backend:
    container_name: backend
    image: eroist/joinhello-backend:latest
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - network-backend

  postgres:
    container_name: postgres
    image: postgres:alpine
    user: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - network-backend
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network-backend:
volumes:
  postgres-data:
    external: true
    name: postgres-data
