version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  aws-cli: circleci/aws-cli@4.0.0
  slack: circleci/slack@4.12.5

executors:
  go:
    docker:
      - image: cimg/go:1.19.3
    environment:
      CGO_ENABLED: 0
      DOCKER_BUILDKIT: 1

commands:
  build-docker-image:
    steps:
      - run:
          name: Build Latest Docker Image
          command: |
            docker build -t joinhello/backend:0.0.1 -f ./docker/Dockerfile .
  publish-docker-image:
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_ACCESS_TOKEN" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker tag joinhello/backend:0.0.1 $DOCKERHUB_USER/joinhello-backend:0.0.1
            docker push $DOCKERHUB_USER/joinhello-backend:0.0.1
  deploy-to-ec2:

jobs:
  build:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - build-docker-image
  publish:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - publish-docker-image
  deploy:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          aws-region: AWS_REGION

workflows:
  joinhello-staging:
    jobs:
      # - build
      # - publish:
      #     context:
      #       - docker-hub-credential
      #     requires:
      #       - build
      - deploy:
          context:
            - aws-credential
          # requires:
          #   - build
