version: 2.1

orbs:
  docker: circleci/docker@2.2.0
  aws-cli: circleci/aws-cli@4.0.0
  slack: circleci/slack@4.12.5

executors:
  go:
    docker:
      - image: cimg/go:1.19.3
    environment:
      CGO_ENABLED: 0
      DOCKER_BUILDKIT: 1

commands:
  build-docker-image:
    steps:
      - run:
          name: Build Latest Docker Image
          command: |
            docker build -t joinhello/backend:0.0.1 -f ./docker/Dockerfile .

jobs:
  build:
    executor: go
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - build-docker-image
