# Start from the alpine3.17 golang base image
FROM golang:alpine

WORKDIR /app

ENV CGO_ENABLED 0
ENV GOPATH /go
ENV GOCACHE /go-build

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./

RUN --mount=type=cache,target=/go/pkg/mod/cache \
    go mod download

CMD ["air", "-c", ".air.toml"]